### ISSUE TITLE
Unknown symbol   Yiisoft\Yii\Bootstrap5\AlertType

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-bootstrap5#161]
### What steps will reproduce the problem? workflow action
https://github.com/rossaddison/invoice/actions/runs/11365127873/job/31612623182

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  8.3
| Operating system | Windows 11

**Comment by terabytesoftw** [comment]
Yes, i'm finishing developing the library, i should update it or lock it in the previous commit until it's released.

**Comment by vjik** [comment]
Hm. It's strange, because this enum exists in dev-master: https://github.com/yiisoft/yii-bootstrap5/blob/master/src/AlertType.php

**Comment by rossaddison** [comment]
This is occuring for its substitute AlertVariant now as well.

**Comment by terabytesoftw** [comment]
Please update your dependencies.

![image](https://github.com/user-attachments/assets/6297506a-6e59-4d0d-bb2d-51803f5b512f)
