### ISSUE TITLE
Yiisoft\Yii\Bootstrap5\Dropdown::items(): Argument #1 must be of type Yiisoft\Yii\Bootstrap5\DropdownItem, array given, called in C:\wamp128\www\invoice\vendor\yiisoft\yii-bootstrap5\src\Nav.php on line 375

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-bootstrap5#188]
### What steps will reproduce the problem?

![image](https://github.com/user-attachments/assets/56f4a435-f402-4fee-8dbe-4c130a212f41)

### Additional info

TypeError: Yiisoft\Yii\Bootstrap5\Dropdown::items(): Argument #1 must be of type Yiisoft\Yii\Bootstrap5\DropdownItem, array given, called in C:\wamp128\www\invoice\vendor\yiisoft\yii-bootstrap5\src\Nav.php on line 375 and defined in C:\wamp128\www\invoice\vendor\yiisoft\yii-bootstrap5\src\Dropdown.php:266
Stack trace:
#0 C:\wamp128\www\invoice\vendor\yiisoft\yii-bootstrap5\src\Nav.php(375): Yiisoft\Yii\Bootstrap5\Dropdown->items(Array)
#1 C:\wamp128\www\invoice\vendor\yiisoft\yii-bootstrap5\src\Nav.php(335): Yiisoft\Yii\Bootstrap5\Nav->renderDropdown(Array, Array)
#2 C:\wamp128\www\invoice\vendor\yiisoft\yii-bootstrap5\src\Nav.php(289): Yiisoft\Yii\Bootstrap5\Nav->renderItem(Array)
#3 C:\wamp128\www\invoice\vendor\yiisoft\yii-bootstrap5\src\Nav.php(124): Yiisoft\Yii\Bootstrap5\Nav->renderItems()
#4 C:\wamp128\www\invoice\vendor\yiisoft\widget\src\Widget.php(133): Yiisoft\Yii\Bootstrap5\Nav->render()
#5 C:\wamp128\www\invoice\resources\views\layout\templates\soletrader\main.php(293): Yiisoft\Widget\Widget->__toString()
#6 C:\wamp128\www\invoice\vendor\yiisoft\view\src\PhpTemplateRenderer.php(28): require('C:\\wamp128\\www\\...')
#7 C:\wamp128\www\invoice\vendor\yiisoft\view\src\PhpTemplateRenderer.php(36): Yiisoft\View\PhpTemplateRenderer->Yiisoft\View\{closure}('C:\\wamp128\\www\\...', Array)
#8 C:\wamp128\www\invoice\vendor\yiisoft\view\src\ViewTrait.php(467): Yiisoft\View\PhpTemplateRenderer->render(Object(Yiisoft\View\WebView), 'C:\\wamp128\\www\\...', Array)
#9 C:\wamp128\www\invoice\vendor\yiisoft\yii-view-renderer\src\ViewRenderer.php(345): Yiisoft\View\WebView->render('C:\\wamp128\\www\\...', Array)
#10 C:\wamp128\www\invoice\vendor\yiisoft\yii-view-renderer\src\ViewRenderer.php(119): Yiisoft\Yii\View\Renderer\ViewRenderer->renderProxy('index', Array, Array, Array, Array, Array)
#11 C:\wamp128\www\invoice\vendor\yiisoft\data-response\src\DataResponse.php(317): Yiisoft\Yii\View\Renderer\ViewRenderer->Yiisoft\Yii\View\Renderer\{closure}()
#12 C:\wamp128\www\invoice\vendor\yiisoft\data-response\src\Formatter\HtmlDataResponseFormatter.php(39): Yiisoft\DataResponse\DataResponse->getData()
#13 C:\wamp128\www\invoice\vendor\yiisoft\data-response\src\DataResponse.php(346): Yiisoft\DataResponse\Formatter\HtmlDataResponseFormatter->format(Object(Yiisoft\DataResponse\DataResponse))
#14 C:\wamp128\www\invoice\vendor\yiisoft\data-response\src\DataResponse.php(99): Yiisoft\DataResponse\DataResponse->formatResponse()
#15 C:\wamp128\www\invoice\vendor\yiisoft\cookies\src\CookieMiddleware.php(148): Yiisoft\DataResponse\DataResponse->getHeader('Set-Cookie')
#16 C:\wamp128\www\invoice\vendor\yiisoft\cookies\src\CookieMiddleware.php(85): Yiisoft\Cookies\CookieMiddleware->encodeResponseSetCookieHeaders(Object(Yiisoft\DataResponse\DataResponse))
#17 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Cookies\CookieMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#18 C:\wamp128\www\invoice\vendor\yiisoft\csrf\src\CsrfTokenMiddleware.php(54): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#19 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Csrf\CsrfTokenMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#20 C:\wamp128\www\invoice\vendor\yiisoft\session\src\SessionMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#21 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Session\SessionMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#22 C:\wamp128\www\invoice\vendor\yiisoft\yii-sentry\src\SentryMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#23 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Sentry\SentryMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#24 C:\wamp128\www\invoice\vendor\yiisoft\error-handler\src\Middleware\ErrorCatcher.php(133): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#25 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\ErrorHandler\Middleware\ErrorCatcher->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#26 C:\wamp128\www\invoice\vendor\yiisoft\request-provider\src\RequestCatcherMiddleware.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#27 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\RequestProvider\RequestCatcherMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#28 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#29 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#30 C:\wamp128\www\invoice\vendor\yiisoft\yii-debug-api\src\Debug\Middleware\MiddlewareDispatcherMiddleware.php(22): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#31 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Api\Debug\Middleware\MiddlewareDispatcherMiddleware->process(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#32 C:\wamp128\www\invoice\vendor\yiisoft\yii-debug-api\src\Debug\Middleware\DebugHeaders.php(26): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#33 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(93): Yiisoft\Yii\Debug\Api\Debug\Middleware\DebugHeaders->process(Object(HttpSoft\Message\ServerRequest), Object(Psr\Http\Server\RequestHandlerInterface@anonymous))
#34 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareStack.php(49): Psr\Http\Server\RequestHandlerInterface@anonymous->handle(Object(HttpSoft\Message\ServerRequest))
#35 C:\wamp128\www\invoice\vendor\yiisoft\middleware-dispatcher\src\MiddlewareDispatcher.php(48): Yiisoft\Middleware\Dispatcher\MiddlewareStack->handle(Object(HttpSoft\Message\ServerRequest))
#36 C:\wamp128\www\invoice\vendor\yiisoft\yii-http\src\Application.php(77): Yiisoft\Middleware\Dispatcher\MiddlewareDispatcher->dispatch(Object(HttpSoft\Message\ServerRequest), Object(App\Handler\NotFoundHandler))
#37 C:\wamp128\www\invoice\vendor\yiisoft\yii-runner-http\src\HttpApplicationRunner.php(159): Yiisoft\Yii\Http\Application->handle(Object(HttpSoft\Message\ServerRequest))
#38 C:\wamp128\www\invoice\public\index.php(43): Yiisoft\Yii\Runner\Http\HttpApplicationRunner->run()
#39 {main}

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by phppress** [comment]
```php
  echo Dropdown::widget()
      ->items(
          DropdownItem::link('Action', '#'),
          DropdownItem::link('Another action', '#'),
          DropdownItem::link('Something else here', '#'),
          DropdownItem::divider(),
          DropdownItem::link('Separated link', '#'),
      )
      ->toggleContent('Toggle dropdown')
      ->toggleVariant(DropdownToggleVariant::DANGER)
      ->toggleSplit()
      ->toggleSplitContent('Danger')
      ->toggleSizeLarge()
      ->render();
  ```
  
  You must update the widget to the latest version.

**Comment by terabytesoftw** [comment]
```php
 echo Dropdown::widget()
     ->items(
         DropdownItem::link('Action', '#'),
         DropdownItem::link('Another action', '#'),
         DropdownItem::link('Something else here', '#'),
         DropdownItem::divider(),
         DropdownItem::link('Separated link', '#'),
     )
     ->toggleContent('Toggle dropdown')
     ->toggleVariant(DropdownToggleVariant::DANGER)
     ->toggleSplit()
     ->toggleSplitContent('Danger')
     ->toggleSizeLarge()
     ->render();
 ```

You must update the widget to the latest version.
