### ISSUE TITLE
The asset manager ended with an error

### ISSUE THREAD

**Issue by chrysos** [yiisoft/yii-bootstrap5#32]
Hello, I updated the composer to version 2.
Replaces fxp/composer-asset-plugin with foxy/foxy.
I decided to install yiisoft/yii-bootstrap5 and I'm having the following errors:

> error Couldn't find any versions for "bootstrap" that matches "^5.0.0"
> 
> [RuntimeException]
>   The asset manager ended with an error

**Comment by Mister-42** [comment]
Remove foxy, add 
```json
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ],
```
to composer config.
