### ISSUE TITLE
Exception during installation

### ISSUE THREAD

**Issue by rezabagheri** [yiisoft/yii-bootstrap5#34]
### What steps will reproduce the problem?
Installation
### What is the expected result?
composer require --prefer-dist yiisoft/yii-bootstrap5
### What do you get instead?

[InvalidArgumentException]                                                                         
  Could not find a version of package yiisoft/yii-bootstrap5 matching your minimum-stability (stabl  
  e). Require it with an explicit version constraint allowing its desired stability.
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 5.alpha
| PHP version      |  PHP 7.4.3 (cli)
| Operating system | Ubuntu 20.04

**Comment by rezabagheri** [comment]
Fixed!
I had to change the 
"minimum-stability": "stable", 
to :
"minimum-stability": "dev",

**Comment by spanceri** [comment]
composer require --prefer-dist yiisoft/yii-bootstrap5


  [InvalidArgumentException]
  Could not find a version of package yiisoft/yii-bootstrap5 matching your minimum-stability (stable). Require it wit
  h an explicit version constraint allowing its desired stability.

**Comment by vjik** [comment]
> [InvalidArgumentException]
> Could not find a version of package yiisoft/yii-bootstrap5 matching your minimum-stability (stable). Require it wit
> h an explicit version constraint allowing its desired stability.

Now package in development. To use it need set option `minimum-stability` in composer.json to `dev`.

Note, this is a package from Yii 3.
