### ISSUE TITLE
NavBar Item and Corousel Item (s) are returning escaped html and will not render as html

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii-bootstrap5#36]
yii-bootstrap5 returns html escaped strings for items after clean setup as online readme

<li class="nav-item">&lt;a class="nav-link" href="/blog"&gt;Blog&lt;/a&gt;</li> <li class="nav-item">&lt;a class="nav-link" href="/blog/comments/"&gt;Comments Feed&lt;/a&gt;</li> <li class="nav-item">&lt;a class="nav-link" href="/user"&gt;Users&lt;/a&gt;</li> <li class="nav-item">&lt;a class="nav-link" href="/contact"&gt;Contact&lt;/a&gt;</li> <li class="nav-item">&lt;a class="nav-link" href="/swagger"&gt;Swagger&lt;/a&gt;</li>
<li class="nav-item">&lt;a class="nav-link" href="/login"&gt;Login&lt;/a&gt;</li> <li class="nav-item">&lt;a class="nav-link" href="/signup"&gt;Signup&lt;/a&gt;</li>

### What steps will reproduce the problem?

- php8.0.4 fresh install - composer 2.0 fresh install
- git clone yiisoft/yii-demo
- follow readme
- open localhost:8080

### What is the expected result?

clean demo bootstrap

### What do you get instead?

elements created with item are returned as escaped html and not as html

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0@dev
| PHP version      |  8.0.4
| Operating system | ubuntu 20.0.4

**Comment by Mister-42** [comment]
Yes, we are working on this as we speak in #35 indeed :)

**Comment by Mister-42** [comment]
PR https://github.com/yiisoft/yii-demo/pull/236 prepared for when #35 is ready
