### ISSUE TITLE
Fresh Instllation: Call to undefined method Yiisoft\Yii\Bootstrap5\Assets\BootstrapAsset::publish()

### ISSUE THREAD

**Issue by strtob** [yiisoft/yii-bootstrap5#44]
### What steps will reproduce the problem?

- fresh github installation of yii2 basic
- install bs5 via composer / packagist repo
- connfigure AppAsset.php like this:
AppAssets.php 
[...]
```
public $depends = [
        'yii\web\YiiAsset',
        'Yiisoft\Yii\Bootstrap5\Assets\BootstrapAsset', // this line
    ];
```
- load page

### What is the expected result?

- no error

### What do you get instead?

vendor/yiisoft/yii2/web/AssetManager.php:

Call to undefined method Yiisoft\Yii\Bootstrap5\Assets\BootstrapAsset::publish()

   ```
 */
    protected function loadBundle($name, $config = [], $publish = true)
    {
        if (!isset($config['class'])) {
            $config['class'] = $name;
        }
        /* @var $bundle AssetBundle */
        $bundle = Yii::createObject($config);
        if ($publish) {
            $bundle->publish($this);
        }
 
        return $bundle;
    }
 
    /**
     * Loads dummy bundle by name.
     *
     * @param string $name
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.0.41
| PHP version     7.4.9  | 
| Operating system debian |

**Comment by rustamwin** [comment]
This package doesn't work with yii2 applications.
