### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by rezabagheri** [yiisoft/yii-bootstrap5#46]
### What steps will reproduce the problem?
Installation
### What do you get instead?
Problem 1
    - Installation request for yiisoft/yii-bootstrap5 ^3.0@dev -> satisfiable by yiisoft/yii-bootstrap5[3.0.x-dev].
    - yiisoft/yii-bootstrap5 3.0.x-dev requires npm-asset/bootstrap ^5.0.0 -> satisfiable by npm-asset/bootstrap[5.0.0-beta3, 5.0.0-beta2, 5.0.0-beta1, 5.0.0-alpha3, 5.0.0-alpha2, 5.0.0-alpha1] but these conflict with your requirements or minimum-stability.

### Additional info

| Q                | A
| --------------- | ---
| Yii version  | 2.0.42-dev    
| PHP version  |  PHP 7.4.3 (cli)
| Operating system | Ubuntu 20.04 LTS

**Comment by samdark** [comment]
What command do you use?

**Comment by rezabagheri** [comment]
Hi,
After installing Yii (Advanced Template), I first remove the default bootstrap:
composer remove yii-bootsrap
And then I installed with this command:
composer require --prefer-dist yiisoft/yii-bootstrap5

**Comment by samdark** [comment]
Ah. That's because this package is for Yii 3, not Yii 2.

**Comment by rezabagheri** [comment]
oops
Sorry and thx

**Comment by ArtMin96** [comment]
is there an option to use in yii2?

**Comment by samdark** [comment]
No.
