### ISSUE TITLE
Q: Bootstrap5 planned for yii2?

### ISSUE THREAD

**Issue by simialbi** [yiisoft/yii-bootstrap5#51]
Bootstrap 5 is stable now and yii3 not ready yet (at least not stable).

Is an official yii2 version planned?

**Comment by simialbi** [comment]
I started with a version here:
[simialbi/yii2-bootstrap5](https://github.com/simialbi/yii2-bootstrap5)

**Comment by samdark** [comment]
> Is an official yii2 version planned?

Well, we may adopt it but have no time to support it ourselves.

**Comment by simialbi** [comment]
Hi @samdark 

What do you mean with adopt? E. g. publish under `yiisoft` and maintained by me?

**Comment by samdark** [comment]
Yes.

**Comment by simialbi** [comment]
Shall I transfer the repository to `yiisoft`?

**Comment by samdark** [comment]
Yes. Thank you.

**Comment by simialbi** [comment]
I can't:
![image](https://user-images.githubusercontent.com/3023342/127745169-ab80b774-e1d3-499f-af75-7fdf0ee4b864.png)

**Comment by samdark** [comment]
You can give me admin permissions in simialbi/yii2-bootstrap5, I'll initiate the transfer and add you to Yii 2 group.

**Comment by simialbi** [comment]
Done

**Comment by samdark** [comment]
Nope, I don't have permissions to access settings.

**Comment by simialbi** [comment]
![image](https://user-images.githubusercontent.com/3023342/127783217-c7454b1d-0e9a-42fc-bac3-380990a84412.png)

**Comment by samdark** [comment]
@simialbi moved. Please check if you have permissions there.

**Comment by samdark** [comment]
I'll set up the rest later today.

**Comment by simialbi** [comment]
@samdark seems to work. Thank you.
