### ISSUE TITLE
Why is cloning the widget required here?

### ISSUE THREAD

**Issue by WeeSee** [yiisoft/yii-bootstrap5#76]
I'm confused about cloning here:

```
public function id(string $value): self
{
    $new = clone $this;
    $new->id = $value;
    return $new;
}
```

Why not just updating `$id`?
```
public function id(string $value): void
{
    $this->id= $value;
}
```

This would only make sense if we had a readonly / immutable property `$id` (PHP8.1). But then, the method name should be changed (e.g. `cloneWithId()`).

What am I missing?

This applies here...
https://github.com/yiisoft/yii-bootstrap5/blob/075765ef078abf923211e6317dcd17ba75c9669b/src/Widget.php#L39

and here...
https://github.com/yiisoft/yii-bootstrap5/blob/075765ef078abf923211e6317dcd17ba75c9669b/src/Widget.php#L66

**Comment by samdark** [comment]
https://github.com/yiisoft/docs/blob/3cd6de071b5205cb39b5b32706634e55b18a2687/018-widgets.md#immutability. Widgets are immutable by default.
