### ISSUE TITLE
Add composer plugins to installation guide

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-bootstrap5#77]
Package required `composer/installers` and `oomphinc/composer-installers-extender` plugins

**Comment by samdark** [comment]
Does it worth doing so? In application templates we have these and in case of interactive installation, it's being asked about by composer itself.

**Comment by luke-** [comment]
@samdark Yes, simply here https://github.com/yiisoft/yii-bootstrap5/pull/128 ?

**Comment by luke-** [comment]
For me, this solves the problem.
