### ISSUE TITLE
It is not possible to mark the "Home" page as active in navbar

### ISSUE THREAD

**Issue by albertborsos** [yiisoft/yii-bootstrap5#80]
This line prevents that to mark the main page as active in my navbar.

https://github.com/yiisoft/yii-bootstrap5/blob/921bb6f2779600185d6ab71145ba7c38ada5b1f7/src/Nav.php#L481

**Comment by terabytesoftw** [comment]
You can try now it should work without problems, thanks for the suggestions we will clean the library completely soon.
